name: flutterexpertdev_github_io
description: The website of flutterexpert.dev
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  gap:
  material_design_icons_flutter:
  flutter_svg:
  url_launcher:
  flex_color_scheme:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/profile/
