name: flutterexpertdev_github_io
description: The website of flutterexpert.dev
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  arb_generator:

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: "l10n_"
  csv_settings:
    delimiter: ";"
    description_index: 1
    base_index: 2
